# Generated by Django 4.1.7 on 2023-03-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Type', models.CharField(choices=[('Chicken', 'Chicken'), ('Catfish', 'Catfish'), ('Goat', 'Goat'), ('Pig or Pork', 'Pig'), ('Otthers. Explain in description', 'Others')], max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Phone_number', models.CharField(max_length=30)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Date', models.DateField()),
                ('Expected_order_recieve_date', models.DateField()),
            ],
        ),
    ]
