# Generated by Django 4.1.7 on 2023-03-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='Expected_order_recieve_date',
            field=models.CharField(max_length=50),
        ),
    ]
