# Generated by Django 4.1.7 on 2023-03-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order_Type',
            field=models.CharField(choices=[('Chicken', 'Chicken'), ('Catfish', 'Catfish'), ('Goat', 'Goat'), ('Pig or Pork', 'Pig'), ('Others. Explain in description', 'Others')], max_length=50),
        ),
    ]
